"""Adding new column to transactions

Revision ID: 7ba372c78f3e
Revises: 0c092860888e
Create Date: 2021-07-19 18:01:31.730199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba372c78f3e'
down_revision = '0c092860888e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transaction_date')
    # ### end Alembic commands ###
